# Configuration goes here in YAML
# These can be called in code with CONFIG[:key]
project_name: "Swagbot"
karma_timeout: 5
nickserv_password: "swagswag"
bugzilla_username: "tiwillia@redhat.com"
bugzilla_password: "yesmam329"
google_api_key: "AIzaSyDFRL1l6W80D7qo1PgoiqNeJXuX664P9Gc"
imgur_client_id: "b13f2f21e81c6ae"
admin_password: "mameshiba"
#irc_server_url: "hyperion.feralhosting.com"
#irc_server_port: 6967
#server_password: "mygooglesgone"
