production:
  adapter: postgresql
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  min_messages: ERROR
  reconnect: false
  pool: 10
  timeout: 5000
  encoding: utf8

development:
  adapter: postgresql
  database: swagbot_development
  username: tiwillia
  password: password
  pool: 10
  timeout: 5000
  encoding: utf8

test:
  adapter: postgresql
  database: swagbot_test
  username: tiwillia
  password: password
  pool: 10
  timeout: 5000
  encoding: utf8
