production:
  adapter: postgresql
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  reconnect: false
  pool: 5
  encoding: utf8

development:
  adapter: postgresql
  database: betabot
  username: tiwillia
  password: snapshot
  host: localhost
  port: 5432

#production:
#  adapter: postgresql
#  database: swagbot
#  username: tiwillia
#  password: snapshot
#  host: localhost
#  port: 5432
